<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jobs</name>
   <tag></tag>
   <elementGuidId>de364e02-f05b-4e01-9421-c156a7ea46a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div[2]/nav/ul/li/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nI-gNb-menuItems__anchorDropdown.nI-gNb-menuItems__anchorDropdown--active > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>826839ef-f36c-42e7-a7f1-2ae4add0f425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jobs</value>
      <webElementGuid>69051465-b294-4405-b19e-fe67b2b08422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;nI-gNb-header&quot;]/div[@class=&quot;nI-gNb-header__wrapper&quot;]/nav[1]/ul[@class=&quot;nI-gNb-menus&quot;]/li[@class=&quot;nI-gNb-menuItems&quot;]/a[@class=&quot;nI-gNb-menuItems__anchorDropdown nI-gNb-menuItems__anchorDropdown--active&quot;]/div[1]</value>
      <webElementGuid>c2daf44a-01d2-410c-a0af-1ee10431839f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Selenium IFrame/iframe_Freshers Now_iframe_b</value>
      <webElementGuid>dd8b2fea-6e51-412e-9caa-c871265ffd4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div[2]/nav/ul/li/a/div</value>
      <webElementGuid>a1f230d8-fb52-4611-a037-86c7a0af4eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular categories'])[1]/preceding::div[1]</value>
      <webElementGuid>7db92dfc-90fa-46c8-adb7-3f62f517d1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT jobs'])[1]/preceding::div[1]</value>
      <webElementGuid>189f1dff-c431-468f-9075-dd9f9fa0ecdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jobs']/parent::*</value>
      <webElementGuid>3fbe30c2-a161-45c2-8646-4b9ad58e1d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>fa6d4959-6e02-48c8-9015-2e70db994f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jobs' or . = 'Jobs')]</value>
      <webElementGuid>daf62585-fd1f-4812-badd-81e44c86b2dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
