<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_November 21, 2019_iframe_a</name>
   <tag></tag>
   <elementGuidId>ea06636b-0145-4b24-922f-c3e7953cd240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='iframe_a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;iframe_a&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dd3a321c-f639-4d98-baed-9dbc5247b9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframe_a</value>
      <webElementGuid>b1eb6358-664e-4dc9-8e11-9d44a04e06e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://freshersnow.com</value>
      <webElementGuid>faf9d9cf-4d14-4cce-814a-4fd9686aa902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-body-9163515251344049321&quot;)/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>e9b5f8bf-7c8a-49dd-a6f7-b89434a72b19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='iframe_a']</value>
      <webElementGuid>7d4fba8c-f1b6-4038-a971-8fac9e0d7624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-9163515251344049321']/div/div/div/div/iframe</value>
      <webElementGuid>a93265e7-88bd-4e98-9b9f-3b1f7e51c301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>eafc71ba-a691-4196-b6bf-b0835ea9932e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'iframe_a' and @src = 'https://freshersnow.com']</value>
      <webElementGuid>7cff18a8-6820-48f6-ab02-e55f7e2ff5c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
