<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Freshers Now_iframe_b</name>
   <tag></tag>
   <elementGuidId>0f99bd3d-e394-4295-9abf-fe139da6d6a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='iframe_b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;iframe_b&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3da1c3c6-6337-4bc5-8d5d-47e5f074a73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframe_b</value>
      <webElementGuid>dc38b527-5a89-41fb-9ca2-ec89fff0d0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://naukri.com</value>
      <webElementGuid>e6b7e177-fc11-42f1-abaa-97743c858616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-body-9163515251344049321&quot;)/div[1]/div[1]/div[1]/div[1]/iframe[2]</value>
      <webElementGuid>59ffc268-a761-4507-9b3b-9880e0c84979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='iframe_b']</value>
      <webElementGuid>5b54991a-54c3-4825-a9ae-96527fe9ffb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-9163515251344049321']/div/div/div/div/iframe[2]</value>
      <webElementGuid>9b7dfb97-bf85-4161-95b5-9d39567acea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>7ad05a65-e40e-4531-b33c-118f12e507dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'iframe_b' and @src = 'https://naukri.com']</value>
      <webElementGuid>0494f3c7-3f13-4c5e-9767-35856457662f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
